src/Entity/Creation.php
<?php

namespace App\Entity;

use App\Repository\CreationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CreationRepository::class)]
class Creation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $tissu = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $remarque = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lien_insta = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTissu(): ?string
    {
        return $this->tissu;
    }

    public function setTissu(?string $tissu): self
    {
        $this->tissu = $tissu;

        return $this;
    }

    public function getRemarque(): ?string
    {
        return $this->remarque;
    }

    public function setRemarque(?string $remarque): self
    {
        $this->remarque = $remarque;

        return $this;
    }

    public function getLienInsta(): ?string
    {
        return $this->lien_insta;
    }

    public function setLienInsta(?string $lien_insta): self
    {
        $this->lien_insta = $lien_insta;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }


}

src/Form/CreationType.php
<?php

namespace App\Form;

use App\Entity\Creation;
use App\Entity\Patron;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class CreationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', DateType::class, [
                'label'=>'  ',
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                 ])
            ->add('tissu', TextType::class, array('label'=>'  '))
            ->add('remarque', TextType::class, array('label'=>'  '))
            ->add('lien_insta', TextType::class, array('label'=>'  '))
            ->add('image', TextType::class, array('label'=>'  '))
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Creation::class,
        ]);
    }
}

src/Controller/CreationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\Creation;
use App\Entity\Patron;
use Symfony\Component\HttpFoundation\Request;
use App\Form\CreationType;


use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class CreationController extends AbstractController
{
    #[Route('/creation', name: 'app_creation')]
    public function index(): Response
    {
        return $this->render('creation/index.html.twig', [
            'controller_name' => 'CreationController',
        ]);
    }

    public function listerCreation(ManagerRegistry $doctrine){
        $repository = $doctrine->getRepository(Creation::class);
        $creation = $repository->findBy(
            [],
            ['date' => 'DESC']
        );
        return $this->render('creation/lister.html.twig', [
            'pCreation' => $creation,]);	
            
    }

    
    /* Fonction consultercreation pour renvoyer toutes les informations d'un creation en fonction de l'id */

    public function consulterCreation(ManagerRegistry $doctrine, int $id){
        $creation = $doctrine->getRepository(Creation::class)->find($id);

        if(!$creation){
            throw $this->createNotFoundException(
                'Aucun creation trouvé avec comme identifiant '.$id
            );
        }
        
        return $this->render('creation/consulter.html.twig', [
        'creation'=>$creation,]);
    }

    public function ajouterCreation(Request $request,ManagerRegistry $doctrine){
        
        $creation = new Creation();
        $form = $this->createForm(CreationType::class, $creation);
        
        $form->handleRequest($request);
     
     
        if ($form->isSubmitted() && $form->isValid()) {

            $creation = $form->getData();
     
            $entityManager = $doctrine->getManager();
            $entityManager->persist($creation);
            $entityManager->flush();
     
            return $this->redirectToRoute('creationAjouter');
        }
        else
        {
            return $this->render('admin/creation/ajouter.html.twig',[
                'form' => $form->createView(),],);
    }
    }
}

templates/creation/consulter.html.twig
{% extends "base.html.twig" %}

{% block title %} Création du {{ creation.date|date("d/m/Y") }}{% endblock %}

{% block creation %} active {% endblock %}

{% block style %}
table{
    height:0px !important;
}
td{
    min-width : 100px !important;
    border-bottom : dotted 1px #634d4d;
    padding-bottom : 5px;
    padding-top : 5px;
}

{% endblock %}



{% block contenu %}

 <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading" id="top" style="background-image: url({{ asset( 'images/banniere_creation.png' ) }});">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>Création du {{ creation.date|date("d/m/Y") }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->


    <div class="container">
        <div class="row">
        <div class="descr-single-product">

            <p id="principal">
                <img class ="imgPatron" src="{{ asset( creation.image ) }}" alt="photo du creation" />
            </p>
            <table class="descrPatron">
            
                <tr>
                    <td>
                        <a href= {{ creation.lienInsta }}>
                            <span style="color: #634d4d !important;font-size: 250% !important;" class="fa-brands fa-instagram"></span>
                        </a>
                    </td>
                    <td> <a class="lien2" href= {{ creation.lienInsta }}>Voir sur Instagram</a></td>
                </tr>

                <tr> 
                    <td class="soustitre">Tissu : </td>
                    <td>{{ creation.tissu }}</td>
                </tr>

                {% if creation.remarque == null %}
                {% else %}
                <tr> 
                    <td class="soustitre">Remarque : </td>
                    <td>
                        {{ creation.remarque }}
                    </td>
                </tr>
                {% endif %}
            </table>

        </div>
</div>
</div>
{% endblock %}

templates/creation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CreationController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Applications/MAMP/htdocs/lesBricolesDeCharlotte/src/Controller/CreationController.php'|file_link(0) }}">src/Controller/CreationController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Applications/MAMP/htdocs/lesBricolesDeCharlotte/templates/creation/index.html.twig'|file_link(0) }}">templates/creation/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/creation/lister.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creation{% endblock %}
{% block creation %} active {% endblock %}

{% block style %}
{% endblock %}

{% block contenu %}
 <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading" id="top" style="background-image: url({{ asset( 'images/banniere_creation.png' ) }});">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>Les créations</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->


    <!-- ***** Products Area Starts ***** -->

	<section class="section" id="products">

    <div class="liste">
        <div class="container">
            <div class="row">
            {% for c in pCreation %}
                <a class="lien" href="{{ path('creationConsulter', { 'id': c.id }) }}">
                <div class="card">
                    <div class="photoCard">
                        <img src="{{ asset( c.image ) }}" alt="image">
                    </div>
                    <div class="descrCard">
                        {{ c.date|date("d/m/Y") }}
                    </div>

                </div>
                </a>
                
            {% endfor %}
            </div>
        </div>
        </div>
    </section>
{% endblock %}